language: go

go:
  - 1.9
  - "1.10"
  - tip

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install musl-tools -y

install:
  - make install-deps

script: |
  make test-full && ./release.sh
